[project]
name = "discord_bot"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "nonebot2[fastapi]",
    "nb-cli",
    "nonebot-adapter-discord",
    "nonebot-plugin-genshinuid",
    "nonebot-plugin-apscheduler",
    "httpx",
    "websockets",
]

[tool.nonebot]
adapters = [{ name = "Discord", module_name = "nonebot.adapters.discord" }]
plugins = ["GenshinUID"]

[tool.nonebot.plugin]
plugin_dirs = []
